### ISSUE TITLE
Import cfg

### ISSUE THREAD

**Issue by DeKugelschieber** [DeKugelschieber/acweb#6]
Add option to load AC cfg files to import existing configurations.

**Comment by venyii** [comment]
Hey there, how do you plan to implement this? I needed it for myself since I really didn't want to enter every preset I have manually to test this, so I built a simple version of it. I'm currently doing everything in the client, I'm able to load a `server_cfg.ini`/`entry_list.ini` and populate the form with those values using a `FileReader`. 

Are you planning to upload and save it directly via server side? Otherwise I could help you out here. Let me know :)

**Comment by DeKugelschieber** [comment]
Hmm I haven't thought about it yet, but your solution sounds very elegant. So if you want to contribute it, just go ahead and create a pull request :)

**Comment by DeKugelschieber** [comment]
Btw. there is a pull request https://github.com/DeKugelschieber/acweb/pull/14 which adds new configuration fields and may break your importer. But it should be easy to add the missing fields afterwards.
